[project]
name = "agentic-team-chat"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "colorama>=0.4.6",
    "dotenv>=0.9.9",
    "langchain>=1.2.7",
    "langchain-openai>=1.1.7",
    "pyttsx3>=2.90",
]
